### ISSUE TITLE
Make CSS framework configurable when starting a new project

### ISSUE THREAD

**Issue by adambezemek** [XCentium/xc-component-library-seed#2]
Currently, in the `master` branch, we are using Tailwind CSS. 
Additionally, there is a branch called `feature/boostrap4` that uses Bootstrap 4.

_Each branch has some slightly different webpack and package.json configurations._ 

**Goal:**  A configuration file (or setup, maybe CLI) that defines the project dependencies before running `npm install` and `npm start`.

**Comment by AdamMornes** [comment]
Completed w/ PR https://github.com/XCentium/xc-component-library-seed/pull/9
